modLoader="javafml"
loaderVersion="[34,)"
license="All Rights Reserved"

# issueTrackerURL="http://my.issue.tracker/"

[[mods]]

modId="wyrmroost"
version="${file.jarVersion}"
displayName="Wyrmroost"
# logoFile="examplemod.png"
#credits="Novacraft: Rooststalker Model and Textures"
authors="WolfShotz, Kingdomall, Shannieann, Ukan"
#description=''' '''

[[dependencies.wyrmroost]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wyrmroost]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"